//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bus_Tickiet_Booking_App_1.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddBus
    {
        public AddBus()
        {
            this.seat = new HashSet<seat>();
        }
    
        public int BusId { get; set; }
        public System.DateTime date { get; set; }
        public string time { get; set; }
        public string from { get; set; }
        public string to { get; set; }
    
        public virtual ICollection<seat> seat { get; set; }
    }
}
