//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bus_Tickiet_Booking_App_1.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class seat
    {
        public int Id { get; set; }
        public int serielnumber_fk { get; set; }
        public string uusername_fk { get; set; }
        public int a1 { get; set; }
        public int a2 { get; set; }
        public int a3 { get; set; }
        public int a4 { get; set; }
        public int b1 { get; set; }
        public int b2 { get; set; }
        public int b3 { get; set; }
        public int b4 { get; set; }
        public int c1 { get; set; }
        public int c2 { get; set; }
        public int c3 { get; set; }
        public int c4 { get; set; }
        public int d1 { get; set; }
        public int d2 { get; set; }
        public int d3 { get; set; }
        public int d4 { get; set; }
        public int e1 { get; set; }
        public int e2 { get; set; }
        public int e3 { get; set; }
        public int e4 { get; set; }
        public bool ConfirmStat { get; set; }
    
        public virtual AddBus AddBus { get; set; }
        public virtual User User { get; set; }
    }
}
